version: '3.8'

services:
  # Unified FastEmbed service (both gRPC and HTTP)
  fastembed:
    build:
      context: .
      dockerfile: Dockerfile
    image: ajacobm/fastembed-qdrant:v2
    container_name: fastembed-v2
    ports:
      - "50051:50051"  # gRPC
      - "50052:50052"  # HTTP API
    volumes:
      # Use host HuggingFace cache for models (read-only)
      - /mnt/c/Users/ADAM/.cache/huggingface:/app/.cache/huggingface:ro
      # Writable cache for FastEmbed-specific files
      - ./cache:/app/.cache:rw
      # Mount .env file explicitly
      - ./.env:/app/.env:ro
      # Mount load_env.sh script
      - ./load_env.sh:/app/load_env.sh:ro
    env_file:
      - .env
    environment:
      - START_MODE=both
      - QDRANT_HOST=host.docker.internal  # Connect to external Kubernetes Qdrant
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50052/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 300s
    restart: unless-stopped
    # Optional: Enable GPU support (comment out for CPU-only)
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu, utility, compute]

  # Alternative: Separate services configuration
  fastembed-grpc:
    build:
      context: .
      dockerfile: Dockerfile
    image: ajacobm/fastembed-qdrant:v2
    container_name: fastembed-grpc-only
    ports:
      - "50051:50051"  # Different port to avoid conflicts
    volumes:
      - /mnt/c/Users/ADAM/.cache/huggingface:/app/.cache/huggingface:ro
      - ./cache:/app/.cache:rw
    env_file:
      - .env
    environment:
      - START_MODE=grpc
      - QDRANT_HOST=host.docker.internal
    healthcheck:
      test: ["CMD-SHELL", "python3 -c \"import grpc; channel = grpc.insecure_channel('localhost:50051'); channel.close()\" || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    profiles:
      - separate  # Only start with --profile separate

  fastembed-http:
    build:
      context: .
      dockerfile: Dockerfile
    image: ajacobm/fastembed-qdrant:v2
    container_name: fastembed-http-only
    ports:
      - "50052:50052"  # Different port to avoid conflicts
    volumes:
      - /mnt/c/Users/ADAM/.cache/huggingface:/app/.cache/huggingface:ro
      - ./cache:/app/.cache:rw
    env_file:
      - .env
    environment:
      - START_MODE=http
      - QDRANT_HOST=host.docker.internal
      - GRPC_HOST=fastembed-grpc-only
      - GRPC_PORT=50051
    depends_on:
      fastembed-grpc:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    profiles:
      - separate  # Only start with --profile separate

# No volumes section needed - using bind mounts for better control
