# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import embed_pb2 as embed__pb2

GRPC_GENERATED_VERSION = '1.73.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in embed_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EmbeddingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetEmbeddings = channel.unary_unary(
                '/proto.EmbeddingService/GetEmbeddings',
                request_serializer=embed__pb2.EmbeddingRequest.SerializeToString,
                response_deserializer=embed__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.LoadModel = channel.unary_unary(
                '/proto.EmbeddingService/LoadModel',
                request_serializer=embed__pb2.LoadModelRequest.SerializeToString,
                response_deserializer=embed__pb2.LoadModelResponse.FromString,
                _registered_method=True)
        self.ProcessFileStream = channel.stream_unary(
                '/proto.EmbeddingService/ProcessFileStream',
                request_serializer=embed__pb2.FileStreamRequest.SerializeToString,
                response_deserializer=embed__pb2.FileStreamResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/proto.EmbeddingService/GetStatus',
                request_serializer=embed__pb2.StatusRequest.SerializeToString,
                response_deserializer=embed__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/proto.EmbeddingService/ListModels',
                request_serializer=embed__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=embed__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.UpdateModelConfig = channel.unary_unary(
                '/proto.EmbeddingService/UpdateModelConfig',
                request_serializer=embed__pb2.UpdateModelConfigRequest.SerializeToString,
                response_deserializer=embed__pb2.UpdateModelConfigResponse.FromString,
                _registered_method=True)


class EmbeddingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetEmbeddings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessFileStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModelConfig(self, request, context):
        """NEW: Update model config and qdrant collection at runtime
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbeddingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetEmbeddings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbeddings,
                    request_deserializer=embed__pb2.EmbeddingRequest.FromString,
                    response_serializer=embed__pb2.EmbeddingResponse.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=embed__pb2.LoadModelRequest.FromString,
                    response_serializer=embed__pb2.LoadModelResponse.SerializeToString,
            ),
            'ProcessFileStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ProcessFileStream,
                    request_deserializer=embed__pb2.FileStreamRequest.FromString,
                    response_serializer=embed__pb2.FileStreamResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=embed__pb2.StatusRequest.FromString,
                    response_serializer=embed__pb2.StatusResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=embed__pb2.ListModelsRequest.FromString,
                    response_serializer=embed__pb2.ListModelsResponse.SerializeToString,
            ),
            'UpdateModelConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModelConfig,
                    request_deserializer=embed__pb2.UpdateModelConfigRequest.FromString,
                    response_serializer=embed__pb2.UpdateModelConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.EmbeddingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.EmbeddingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmbeddingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.EmbeddingService/GetEmbeddings',
            embed__pb2.EmbeddingRequest.SerializeToString,
            embed__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.EmbeddingService/LoadModel',
            embed__pb2.LoadModelRequest.SerializeToString,
            embed__pb2.LoadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessFileStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/proto.EmbeddingService/ProcessFileStream',
            embed__pb2.FileStreamRequest.SerializeToString,
            embed__pb2.FileStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.EmbeddingService/GetStatus',
            embed__pb2.StatusRequest.SerializeToString,
            embed__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.EmbeddingService/ListModels',
            embed__pb2.ListModelsRequest.SerializeToString,
            embed__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModelConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.EmbeddingService/UpdateModelConfig',
            embed__pb2.UpdateModelConfigRequest.SerializeToString,
            embed__pb2.UpdateModelConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
